services:
  oms_web:
    container_name: oms_web
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
      - ./.env.db
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./oms:/home/app/web/
    depends_on:
      - oms_db

  oms_db:
    image: postgres:16
    container_name: oms_db
    restart: unless-stopped
    env_file:
      - ./.env.db
    volumes:
      - oms_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  oms_data: